name: test

on:
  pull_request:
  push:

jobs:
  test-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build --no-link
      - run: nix build --no-link '.#pytest-icecream-tests'
      - run: nix develop -c sh -c "PYTHONPATH=.:\$PYTHONPATH python -m pytest -vvv"
      - run: nix flake check --all-systems

  test-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip3 install -U setuptools pip '.[test]'
      - run: pip3 uninstall -y pytest-icecream && rm -r ./build
      - run: PYTHONPATH=.:$PYTHONPATH python -m pytest -vvv

  lint-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix develop -c pre-commit run -av

  lint-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip3 install -U setuptools pip '.[test]'
      - run: pip3 uninstall -y pytest-icecream && rm -r ./build
      - run: pre-commit run -av
